### PR TITLE
Align with Go SDK

### LINKED ISSUE #4: Write a README
Write a simple README that shows how to get started with sdk-python and shows some usage examples.

### LINKED ISSUE #5: Align with Go SDK & spec
The Go SDK, and the CDEvents specification, has changed since the current iteration of the Python SDK was developed. The Python SDK should be updated to reflect these changes.

### PR DESCRIPTION
**Pull request by erkist**
Fixes #<issuelink>

## One line description for the changelog

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by afrittoli** [comment]
@erkist Thanks for this PR. 
@elmsdata is interested in contributing to the Python SDK - would you be able to hand over the work you've done on this until you have time to contribute again?

**Comment by elmsdata** [comment]
> @erkist Thanks for this PR. @elmsdata is interested in contributing to the Python SDK - would you be able to hand over the work you've done on this until you have time to contribute again?

Hi @erkist and happy Monday! Happy to help anyway that I can, I see 106 file changes in this pull request so let me know where the best place to start! I am currently using the Java SDK to build a Jenkins plugin so I have already read and used one of the SDKs!

**Comment by erkist** [comment]
@afrittoli @elmsdata Sounds awesome!

The current state of this PR is (or was, when it was created) that it can create valid CDEvent messages (specifically messages that pass schema validation).

For what to do next, I think the main thing would be to be able to parse incoming events. I believe the CloudEvents SDK use [Pydantic](https://docs.pydantic.dev/) for this so I think it would make sense for our SDK to use it as well? But I'll leave the choice up to you @elmsdata if you decide to implement it.

Other things to look into is improved documentation with examples, and alignment with the latest changes in the CDEvents spec.

Let me know if there is something I can do to help, I can absolutely find a few minutes here and there to help.

**Comment by elmsdata** [comment]
> oved documentation with examples, and alignment with t

Fantastic, I would love to help build Pydantic into the SDK! For the documentation, I am looking into automated capabilities to generate the readme for the SDK. Might try creating a Github Action, just an exploratory idea right now! 

For the current state of this pull request, would it be better to merge it to main and then I create a new feature branch? Or is there anything you would like updated in this pull request before it's merged? Thanks!

**Comment by afrittoli** [comment]
> Fixes #
> 
> ## Changes
> ## One line description for the changelog
> * [ ]  Tests pass
> * [ ]  Appropriate changes to README are included in PR

Can we have a better PR description here before this is merged? ^^^

**Review by elmsdata — APPROVED** [review]
Looks great!

**Pull request merged**
