### PR TITLE
chore: add pre-commit job and change test job in CI workflow

### LINKED ISSUE #2: Fix GitHub actions/workflow
Currently the GitHub workflows at https://github.com/cdevents/sdk-python/blob/skeleton-project/.github/workflows/main.yml are copied from a template and don't apply to the project.

The workflow for Pull requests should be updated to run two actions:
1. pre-commit run --all-files
2. Run pytest tests for both CLI and Core

### PR DESCRIPTION
**Pull request by randomnoise**
Fixes #2.

## Changes
- added pre-commit job in CI worklow
- change test jobs to working state in CI workflow

### CODE REVIEW

**Comment by randomnoise** [comment]
Pre-commit job failed and this is expected. When I run `make check` (which is `pre-commit run --all-files`), I get the same errors on a local dev environment.

image

**Comment by erkist** [comment]
Awesome, thanks for the PR! I will see if I can fix the underlying errors so that the check runs successfully in the pipeline as well.

**Comment by erkist** [comment]
@randomnoise If you rebase this PR on latest `main` I hope it will fix the pipeline issues.

**Comment by randomnoise** [comment]
Thanks for the update @erkist  and the work on pre-commit fixes with #8.

I rebased my branch on latest `main`. I cannot start a re-test on this repo; but I tested on my fork, it seems your latest commit fixed the pre-commit errors for pre-commit CI job 👍

Result: https://github.com/randomnoise/sdk-python/actions/runs/3185336130

image

**Comment by erkist** [comment]
The new workflow works great! Thank you very much for the contribution @randomnoise! It will really help us as we are going to do quite a few updates to the SDK for the 0.1 release of CDEvents and it is great to have automated verification in place. 🥇

**Pull request merged**
